; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.28"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[adminimal_admin_menu][subdir] = "contrib"
projects[adminimal_admin_menu][version] = "1.5"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.1"

projects[better_watchdog_ui][subdir] = "contrib"
projects[better_watchdog_ui][version] = "2.0"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.14"

projects[coffee][subdir] = "contrib"
projects[coffee][version] = "2.2"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[search_krumo][subdir] = "contrib"
projects[search_krumo][version] = "1.5"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

; Themes
projects[adminimal_theme][subdir] = "contrib"
projects[adminimal_theme][version] = "1.5"



